In [1]:
import pandas as pd
import numpy as np

In [2]:
df_age_19=pd.read_csv('AgeData/df_age_19.csv',index_col=0)
df_age_20=pd.read_csv('AgeData/df_age_20.csv',index_col=0)
df_age_21=pd.read_csv('AgeData/df_age_21.csv',index_col=0)
df_age_22=pd.read_csv('AgeData/df_age_22.csv',index_col=0)
df_age_23=pd.read_csv('AgeData/df_age_23.csv',index_col=0)
df_age_24=pd.read_csv('AgeData/df_age_24.csv',index_col=0)
df_age_25=pd.read_csv('AgeData/df_age_25.csv',index_col=0)
df_age_26=pd.read_csv('AgeData/df_age_26.csv',index_col=0)
df_age_27=pd.read_csv('AgeData/df_age_27.csv',index_col=0)
df_age_28=pd.read_csv('AgeData/df_age_28.csv',index_col=0)
df_age_29=pd.read_csv('AgeData/df_age_29.csv',index_col=0)

df_age_30=pd.read_csv('AgeData/df_age_30.csv',index_col=0)
df_age_31=pd.read_csv('AgeData/df_age_31.csv',index_col=0)
df_age_32=pd.read_csv('AgeData/df_age_32.csv',index_col=0)
df_age_33=pd.read_csv('AgeData/df_age_33.csv',index_col=0)
df_age_34=pd.read_csv('AgeData/df_age_34.csv',index_col=0)
df_age_35=pd.read_csv('AgeData/df_age_35.csv',index_col=0)
df_age_36=pd.read_csv('AgeData/df_age_36.csv',index_col=0)
df_age_37=pd.read_csv('AgeData/df_age_37.csv',index_col=0)
df_age_38=pd.read_csv('AgeData/df_age_38.csv',index_col=0)
df_age_39=pd.read_csv('AgeData/df_age_39.csv',index_col=0)

In [3]:
df_age_19.head()

TOT  age_x  age_y  assists_ev  assists_pp  assists_sh  blocks  \
7   FLA     19     19          16           4           0      35   
15  WSH     19     19          12           1           0      18   
29  MTL     19     19           2           0           0      24   
34  TBL     19     19          25           3           0      17   
37  NYR     19     19           5           1           0       5   

    corsi_against  corsi_for  corsi_pct       ...         season  shot_pct  \
7             851        954       52.9       ...        2014-15      13.0   
15            545        669       55.1       ...        2014-15      13.8   
29            389        302       43.7       ...        2014-15      10.5   
34            647        752       53.8       ...        2014-15       5.3   
37            159        171       51.8       ...        2014-15       5.6   

    shot_pct.1  shots_attempted  shots_attempted.1  takeaways  \
7         13.0              199                199         42   
15        13.8              142                142         18   
29        10.5               67                 67          6   
34         5.3              155                155         36   
37         5.6               36                 36          5   

    time_on_ice_avg  uniqueseason  zs_defense_pct  zs_offense_pct  
7             17.30             1            51.0            49.0  
15            12.55             1            36.5            63.5  
29            13.48             1            64.7            35.3  
34            13.14             1            40.8            59.2  
37            12.09             1            38.2            61.8  

[5 rows x 38 columns]

In [74]:
df_age_19=pd.read_csv('AgeData/df_age_19.csv',index_col=0)

In [75]:
df_age_19['goals_all']=df_age_19['goals_ev']+df_age_19['goals_pp']+df_age_19['goals_sh']
df_age_19['goals_all']=df_age_19['goals_all']/df_age_19['games_played']
df_age_19['goals_ev']=df_age_19['goals_ev']/df_age_19['games_played']
df_age_19['goals_pp']=df_age_19['goals_pp']/df_age_19['games_played']
df_age_19['goals_sh']=df_age_19['goals_sh']/df_age_19['games_played']

df_age_19['assists_all']=df_age_19['assists_ev']+df_age_19['assists_pp']+df_age_19['assists_sh']
df_age_19['assists_all']=df_age_19['assists_all']/df_age_19['games_played']
df_age_19['assists_ev']=df_age_19['assists_ev']/df_age_19['games_played']
df_age_19['assists_pp']=df_age_19['assists_pp']/df_age_19['games_played']
df_age_19['assists_sh']=df_age_19['assists_sh']/df_age_19['games_played']

df_age_19['shots_attempted']=df_age_19['shots_attempted']/df_age_19['games_played']

In [76]:
df_age_19_nn=df_age_19[['goals_all','goals_pp','goals_sh','assists_ev','assists_pp','assists_sh','shots_attempted','age_x']]

In [77]:
df_age_19_nn.head()

goals_all  goals_pp  goals_sh  assists_ev  assists_pp  assists_sh  \
7    0.225352  0.042254  0.000000    0.225352    0.056338           0   
15   0.169811  0.037736  0.000000    0.226415    0.018868           0   
29   0.121212  0.000000  0.030303    0.060606    0.000000           0   
34   0.057143  0.042857  0.000000    0.357143    0.042857           0   
37   0.055556  0.000000  0.000000    0.277778    0.055556           0   

    shots_attempted  age_x  
7          2.802817     19  
15         2.679245     19  
29         2.030303     19  
34         2.214286     19  
37         2.000000     19

In [78]:
set(df_age_19_nn['age_x'])

{19.0}

In [69]:
cols_to_norm = ['goals_pp','goals_sh','assists_ev','assists_pp','assists_sh','shots_attempted','age_x']
df_age_19_nn[cols_to_norm] = df_age_19_nn[cols_to_norm].apply(lambda x: (x - x.mean()) / (x.max() - x.min()))

In [71]:
df_age_19_nn=df_age_19_nn[['assists_ev','assists_pp','assists_sh','shots_attempted','age_x']]

In [72]:
df_age_19_nn.head()

assists_ev  assists_pp  assists_sh  shots_attempted  age_x
7     0.140468   -0.021996   -0.020921        -0.018496    NaN
15    0.142745   -0.168308   -0.020921        -0.039813    NaN
29   -0.212560   -0.241982   -0.020921        -0.151763    NaN
34    0.422876   -0.074635   -0.020921        -0.120024    NaN
37    0.252808   -0.025051   -0.020921        -0.156990    NaN

In [18]:
numpyMatrix = df_age_19_nn.as_matrix()

In [19]:
numpyMatrix

array([[ 0.14046768, -0.02199568, -0.02092104, -0.01849576],
       [ 0.1427455 , -0.16830751, -0.02092104, -0.03981317],
       [-0.21255957, -0.24198227, -0.02092104, -0.15176253],
       [ 0.42287642, -0.07463533, -0.02092104, -0.12002358],
       [ 0.25280839, -0.02505105, -0.02092104, -0.15699012],
       [ 0.03572156, -0.24198227, -0.02092104, -0.14176861],
       [-0.00847794,  0.11299609, -0.02092104,  0.00207802],
       [-0.05458322, -0.24198227, -0.02092104, -0.07717182],
       [-0.00991739, -0.04001182, -0.02092104, -0.11534965],
       [ 0.32721315,  0.00206535, -0.02092104,  0.36862786],
       [-0.11385827, -0.0337283 , -0.02092104,  0.0730239 ],
       [-0.17759454, -0.24198227, -0.02092104, -0.19680024],
       [-0.07457256, -0.24198227, -0.02092104, -0.09229868],
       [-0.3424297 , -0.24198227, -0.02092104, -0.15699012],
       [-0.21637928, -0.24198227, -0.02092104, -0.06058719],
       [-0.02100113, -0.04674417, -0.02092104, -0.20299293],
       [ 0.01935137,  0.

In [20]:
df_age_19['goals_all'].as_matrix()

array([ 0.22535211,  0.16981132,  0.12121212,  0.05714286,  0.05555556,
        0.19117647,  0.07792208,  0.08955224,  0.15517241,  0.21875   ,
        0.29333333,  0.02564103,  0.        ,  0.        ,  0.05882353,
        0.05      ,  0.23376623,  0.05405405,  0.20833333,  0.19230769,
        0.2       ,  0.        ,  0.2875    ,  0.13043478,  0.        ,
        0.27272727,  0.29411765,  0.        ,  0.12727273,  0.13636364,
        0.11111111,  0.05882353,  0.2962963 ,  0.05063291,  0.16666667,
        0.        ,  0.30434783,  0.35555556,  0.        ,  0.        ,
        0.23809524,  0.09090909,  0.375     ,  0.375     ,  0.07246377,
        0.1038961 ,  0.5       ,  0.27160494,  0.22222222,  0.05128205,
        0.14634146,  0.17241379,  0.375     ,  0.        ,  0.21052632,
        0.04444444,  0.25609756,  0.        ,  0.20967742,  0.02      ,
        0.375     ,  0.12698413,  0.1125    ,  0.10294118,  0.14102564,
        0.12345679,  0.1125    ,  0.07407407,  0.15384615,  0.08

In [27]:
#New complete class, with changes:
class Neural_Network(object):
    def __init__(self, Lambda=0):        
        #Define Hyperparameters
        self.inputLayerSize = 4
        self.outputLayerSize = 1
        self.hiddenLayerSize = 2
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
        #Regularization Parameter:
        self.Lambda = Lambda
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)/X.shape[0] + (self.Lambda/2)*(np.sum(self.W1**2)+np.sum(self.W2**2))
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        #Add gradient of regularization term:
        dJdW2 = np.dot(self.a2.T, delta3)/X.shape[0] + self.Lambda*self.W2
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        #Add gradient of regularization term:
        dJdW1 = np.dot(X.T, delta2)/X.shape[0] + self.Lambda*self.W1
        
        return dJdW1, dJdW2
    
    #Helper functions for interacting with other methods/classes
    def getParams(self):
        #Get W1 and W2 Rolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single parameter vector:
        W1_start = 0
        W1_end = self.hiddenLayerSize*self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], \
                             (self.inputLayerSize, self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], \
                             (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))

In [28]:
import matplotlib.pyplot as plt

In [351]:
plt.plot(T.J)
plt.grid(1)
plt.xlabel('Iterations')
plt.ylabel('Cost')
plt.show()

In [29]:
NN = Neural_Network()

In [30]:
X = numpyMatrix
data_list = list(df_age_19['goals_all'])

In [31]:
i=0
y=[]
while i<len(data_list):
    y.append(data_list[i:i+1])
    i=i+1

In [32]:
yHat = NN.forward(X)
#print y
#print np.array(y)

In [33]:
epsilon = 1e-4
x = 1.5

In [34]:
print len(yHat)
print len(data_list)

173
173


In [35]:
cost1 = NN.costFunction(X,y)
print cost1

[ 0.0216338]


In [37]:
def computeNumericalGradient(N, X, y):
    paramsInitial = N.getParams()
    numgrad = np.zeros(paramsInitial.shape)
    perturb = np.zeros(paramsInitial.shape)
    e = 1e-4

    for p in range(len(paramsInitial)):
        #Set perturbation vector
        perturb[p] = e
        N.setParams(paramsInitial + perturb)
        loss2 = N.costFunction(X, y)

        N.setParams(paramsInitial - perturb)
        loss1 = N.costFunction(X, y)

        #Compute Numerical Gradient
        numgrad[p] = (loss2 - loss1) / (2*e)

        #Return the value we changed to zero:
        perturb[p] = 0

    #Return Params to original value:
    N.setParams(paramsInitial)

    return numgrad 

In [39]:
##Need to modify trainer class a bit to check testing error during training:
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))
        self.testJ.append(self.N.costFunction(self.testX, self.testY))
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = computeNumericalGradient(self.N, X, y)
        
        return cost, grad
        
    def train(self, trainX, trainY, testX, testY):
        #Make an internal variable for the callback function:
        self.X = trainX
        self.y = trainY
        
        self.testX = testX
        self.testY = testY

        #Make empty list to store training costs:
        self.J = []
        self.testJ = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(trainX, trainY), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res


In [40]:
computeNumericalGradient(NN, X, y)

array([  3.25223924e-04,   5.38728856e-04,   4.36166170e-04,
         6.66151156e-04,   9.03198400e-05,   1.43187401e-04,
         3.91041409e-04,   6.01774091e-04,   1.89709718e-02,
         1.87474695e-02])

In [42]:
T = trainer(NN)

In [51]:
print len(X)
print len(y)

173
173


In [43]:
trainX=X[:140]
trainY=y[:140]
testX=X[140:]
testY=y[140:]

In [48]:
NN = Neural_Network(Lambda=0.0001)

In [49]:
#Make sure our gradients our correct after making changes:
numgrad = computeNumericalGradient(NN, X, y)
#grad = NN.computeGradients(X,y)

In [45]:
from scipy import optimize

In [52]:
NN = Neural_Network()

T = trainer(NN)
T.train(trainX, trainY, testX, testY)

Optimization terminated successfully.
         Current function value: 0.004264
         Iterations: 112
         Function evaluations: 119
         Gradient evaluations: 119


In [53]:
#Plot cost during training:
plt.plot(T.J)
plt.plot(T.testJ)
plt.grid(1)
plt.xlabel('Iterations')
plt.ylabel('Cost')
plt.show()

In [87]:
import matplotlib.pyplot as plt

In [88]:
plt.plot(T.J)
plt.grid(1)
plt.xlabel('Iterations')
plt.ylabel('Cost')
plt.show()

In [93]:
##Need to modify trainer class a bit to check testing error during training:
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))
        self.testJ.append(self.N.costFunction(self.testX, self.testY))
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = computeNumericalGradient(self.N, X, y)
        
        return cost, grad
        
    def train(self, trainX, trainY, testX, testY):
        #Make an internal variable for the callback function:
        self.X = trainX
        self.y = trainY
        
        self.testX = testX
        self.testY = testY

        #Make empty list to store training costs:
        self.J = []
        self.testJ = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(trainX, trainY), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res


In [60]:
def computeNumericalGradient(N, X, y):
        paramsInitial = N.getParams()
        numgrad = np.zeros(paramsInitial.shape)
        perturb = np.zeros(paramsInitial.shape)
        e = 1e-4
        #print paramsInitial
        for p in range(len(paramsInitial)):
            #Set perturbation vector
            perturb[p] = e
            N.setParams(paramsInitial + perturb)
            loss2 = N.costFunction(X, y)
            
            N.setParams(paramsInitial - perturb)
            loss1 = N.costFunction(X, y)

            #Compute Numerical Gradient
            #print loss1
            #print loss2
            numgrad[p] = (loss2 - loss1) / (2*e)

            #Return the value we changed to zero:
            perturb[p] = 0
            
        #Return Params to original value:
        N.setParams(paramsInitial)

        return numgrad 

In [50]:
X

array([[ 0.14046768, -0.02199568, -0.02092104, -0.01849576],
       [ 0.1427455 , -0.16830751, -0.02092104, -0.03981317],
       [-0.21255957, -0.24198227, -0.02092104, -0.15176253],
       [ 0.42287642, -0.07463533, -0.02092104, -0.12002358],
       [ 0.25280839, -0.02505105, -0.02092104, -0.15699012],
       [ 0.03572156, -0.24198227, -0.02092104, -0.14176861],
       [-0.00847794,  0.11299609, -0.02092104,  0.00207802],
       [-0.05458322, -0.24198227, -0.02092104, -0.07717182],
       [-0.00991739, -0.04001182, -0.02092104, -0.11534965],
       [ 0.32721315,  0.00206535, -0.02092104,  0.36862786],
       [-0.11385827, -0.0337283 , -0.02092104,  0.0730239 ],
       [-0.17759454, -0.24198227, -0.02092104, -0.19680024],
       [-0.07457256, -0.24198227, -0.02092104, -0.09229868],
       [-0.3424297 , -0.24198227, -0.02092104, -0.15699012],
       [-0.21637928, -0.24198227, -0.02092104, -0.06058719],
       [-0.02100113, -0.04674417, -0.02092104, -0.20299293],
       [ 0.01935137,  0.

In [51]:
yHat

array([[-0.04228285],
       [ 0.04526993],
       [ 0.16415762],
       [-0.12846966],
       [-0.12130602],
       [ 0.09165907],
       [-0.07788506],
       [ 0.14102992],
       [-0.01722857],
       [ 0.01546242],
       [ 0.07393705],
       [ 0.13829059],
       [ 0.14203866],
       [ 0.20207994],
       [ 0.19606104],
       [-0.03899589],
       [-0.00890496],
       [ 0.03177514],
       [-0.06181831],
       [ 0.00549444],
       [ 0.30675933],
       [ 0.23438839],
       [ 0.16555518],
       [ 0.1132388 ],
       [-0.03557042],
       [-0.03289179],
       [ 0.10584953],
       [ 0.05178455],
       [ 0.19831919],
       [-0.18038409],
       [ 0.01696135],
       [ 0.18839636],
       [-0.16500012],
       [-0.001014  ],
       [-0.00599857],
       [ 0.24569635],
       [-0.22453451],
       [-0.64078929],
       [ 0.19561825],
       [ 0.12515345],
       [-0.3892669 ],
       [-0.14254371],
       [-0.34655006],
       [-0.34655006],
       [-0.37506997],
       [-0

In [59]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 4
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))
        

In [57]:
def computeNumericalGradient(N, X, y):
        paramsInitial = N.getParams()
        numgrad = np.zeros(paramsInitial.shape)
        perturb = np.zeros(paramsInitial.shape)
        e = 1e-4

        for p in range(len(paramsInitial)):
            #Set perturbation vector
            perturb[p] = e
            N.setParams(paramsInitial + perturb)
            loss2 = N.costFunction(X, y)
            
            N.setParams(paramsInitial - perturb)
            loss1 = N.costFunction(X, y)

            #Compute Numerical Gradient
            numgrad[p] = (loss2 - loss1) / (2*e)

            #Return the value we changed to zero:
            perturb[p] = 0
            
        #Return Params to original value:
        N.setParams(paramsInitial)

        return numgrad 

In [58]:
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))   
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = computeNumericalGradient(self.N, X, y)
        
        return cost, grad
        
    def train(self, X, y):
        #Make an internal variable for the callback function:
        self.X = X
        self.y = y

        #Make empty list to store costs:
        self.J = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(X, y), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res
    

In [56]:
from scipy import optimize