In [2]:
import pandas as pd
import numpy as np

In [22]:
df_age_19=pd.read_csv('AgeData/df_age_19.csv',index_col=0)
df_age_20=pd.read_csv('AgeData/df_age_20.csv',index_col=0)
df_age_21=pd.read_csv('AgeData/df_age_21.csv',index_col=0)
df_age_22=pd.read_csv('AgeData/df_age_22.csv',index_col=0)
df_age_23=pd.read_csv('AgeData/df_age_23.csv',index_col=0)
df_age_24=pd.read_csv('AgeData/df_age_24.csv',index_col=0)
df_age_25=pd.read_csv('AgeData/df_age_25.csv',index_col=0)
df_age_26=pd.read_csv('AgeData/df_age_26.csv',index_col=0)
df_age_27=pd.read_csv('AgeData/df_age_27.csv',index_col=0)
df_age_28=pd.read_csv('AgeData/df_age_28.csv',index_col=0)
df_age_29=pd.read_csv('AgeData/df_age_29.csv',index_col=0)

df_age_30=pd.read_csv('AgeData/df_age_30.csv',index_col=0)
df_age_31=pd.read_csv('AgeData/df_age_31.csv',index_col=0)
df_age_32=pd.read_csv('AgeData/df_age_32.csv',index_col=0)
df_age_33=pd.read_csv('AgeData/df_age_33.csv',index_col=0)
df_age_34=pd.read_csv('AgeData/df_age_34.csv',index_col=0)
df_age_35=pd.read_csv('AgeData/df_age_35.csv',index_col=0)
df_age_36=pd.read_csv('AgeData/df_age_36.csv',index_col=0)
df_age_37=pd.read_csv('AgeData/df_age_37.csv',index_col=0)
df_age_38=pd.read_csv('AgeData/df_age_38.csv',index_col=0)
df_age_39=pd.read_csv('AgeData/df_age_39.csv',index_col=0)

In [23]:
df_age_19.head()

TOT  age_x  age_y  assists_ev  assists_pp  assists_sh  blocks  \
7   FLA     19     19          16           4           0      35   
15  WSH     19     19          12           1           0      18   
29  MTL     19     19           2           0           0      24   
34  TBL     19     19          25           3           0      17   
37  NYR     19     19           5           1           0       5   

    corsi_against  corsi_for  corsi_pct       ...         season  shot_pct  \
7             851        954       52.9       ...        2014-15      13.0   
15            545        669       55.1       ...        2014-15      13.8   
29            389        302       43.7       ...        2014-15      10.5   
34            647        752       53.8       ...        2014-15       5.3   
37            159        171       51.8       ...        2014-15       5.6   

    shot_pct.1  shots_attempted  shots_attempted.1  takeaways  \
7         13.0              199                199         42   
15        13.8              142                142         18   
29        10.5               67                 67          6   
34         5.3              155                155         36   
37         5.6               36                 36          5   

    time_on_ice_avg  uniqueseason  zs_defense_pct  zs_offense_pct  
7             17.30             1            51.0            49.0  
15            12.55             1            36.5            63.5  
29            13.48             1            64.7            35.3  
34            13.14             1            40.8            59.2  
37            12.09             1            38.2            61.8  

[5 rows x 38 columns]

In [86]:
df_age_19.columns

Index([u'TOT', u'age_x', u'age_y', u'assists_ev', u'assists_pp', u'assists_sh',
       u'blocks', u'corsi_against', u'corsi_for', u'corsi_pct',
       u'corsi_rel_pct', u'fenwick_against', u'fenwick_for', u'fenwick_pct',
       u'fenwick_rel_pct', u'games_played', u'giveaways', u'goals_ev',
       u'goals_gw', u'goals_pp', u'goals_sh', u'hits', u'name',
       u'on_ice_shot_pct', u'on_ice_sv_pct', u'pdo', u'pen_min', u'plus_minus',
       u'season', u'shot_pct', u'shot_pct.1', u'shots_attempted',
       u'shots_attempted.1', u'takeaways', u'time_on_ice_avg', u'uniqueseason',
       u'zs_defense_pct', u'zs_offense_pct', u'goals_all', u'assists_all'],
      dtype='object')

In [155]:
df_age_19=pd.read_csv('AgeData/df_age_19.csv',index_col=0)

In [156]:
df_age_19['goals_all']=df_age_19['goals_ev']+df_age_19['goals_pp']+df_age_19['goals_sh']
#df_age_19['goals_all']=df_age_19['goals_all']/df_age_19['games_played']
df_age_19['goals_ev']=df_age_19['goals_ev']/df_age_19['games_played']
df_age_19['goals_pp']=df_age_19['goals_pp']/df_age_19['games_played']
df_age_19['goals_sh']=df_age_19['goals_sh']/df_age_19['games_played']

df_age_19['assists_all']=df_age_19['assists_ev']+df_age_19['assists_pp']+df_age_19['assists_sh']
#df_age_19['assists_all']=df_age_19['assists_all']/df_age_19['games_played']
df_age_19['assists_ev']=df_age_19['assists_ev']/df_age_19['games_played']
df_age_19['assists_pp']=df_age_19['assists_pp']/df_age_19['games_played']
df_age_19['assists_sh']=df_age_19['assists_sh']/df_age_19['games_played']

df_age_19['shots_attempted']=df_age_19['shots_attempted']/df_age_19['games_played']

In [157]:
df_age_19_nn=df_age_19[['goals_all','goals_pp','goals_sh','assists_ev','assists_pp','assists_sh','shots_attempted']]

In [158]:
df_age_19_nn.head()

goals_all  goals_pp  goals_sh  assists_ev  assists_pp  assists_sh  \
7          16  0.042254  0.000000    0.225352    0.056338           0   
15          9  0.037736  0.000000    0.226415    0.018868           0   
29          4  0.000000  0.030303    0.060606    0.000000           0   
34          4  0.042857  0.000000    0.357143    0.042857           0   
37          1  0.000000  0.000000    0.277778    0.055556           0   

    shots_attempted  
7          2.802817  
15         2.679245  
29         2.030303  
34         2.214286  
37         2.000000

In [159]:
cols_to_norm = ['goals_pp','goals_sh','assists_ev','assists_pp','assists_sh','shots_attempted']
df_age_19_nn[cols_to_norm] = df_age_19_nn[cols_to_norm].apply(lambda x: (x - x.mean()) / (x.max() - x.min()))

In [160]:
df_age_19_nn=df_age_19_nn[['assists_ev','assists_pp','assists_sh','shots_attempted']]

In [161]:
df_age_19_nn.head()

assists_ev  assists_pp  assists_sh  shots_attempted
7     0.140468   -0.021996   -0.020921        -0.018496
15    0.142745   -0.168308   -0.020921        -0.039813
29   -0.212560   -0.241982   -0.020921        -0.151763
34    0.422876   -0.074635   -0.020921        -0.120024
37    0.252808   -0.025051   -0.020921        -0.156990

In [246]:
numpyMatrix = df_age_19_nn.head(4).as_matrix()

In [247]:
numpyMatrix

array([[ 0.14046768, -0.02199568, -0.02092104, -0.01849576],
       [ 0.1427455 , -0.16830751, -0.02092104, -0.03981317],
       [-0.21255957, -0.24198227, -0.02092104, -0.15176253],
       [ 0.42287642, -0.07463533, -0.02092104, -0.12002358]])

In [248]:
df_age_19['goals_all'][:4].as_matrix()

array([ 16.,   9.,   4.,   4.])

In [343]:
T = trainer(NN)

In [344]:
T.train(X,y)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 20
         Function evaluations: 27
         Gradient evaluations: 27


In [346]:
import matplotlib.pyplot as plt

In [351]:
plt.plot(T.J)
plt.grid(1)
plt.xlabel('Iterations')
plt.ylabel('Cost')
plt.show()

In [327]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 4
        self.outputLayerSize = 1
        self.hiddenLayerSize = 2
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        #self.a2 = self.sigmoid(self.z2)
        yHat = np.dot(self.z2, self.W2)
        self.yHat=yHat
        #yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        
        self.yHat = self.forward(X)
        
        J = 0.5*sum((y-self.yHat)**2)
        
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        print 'yhat'
        print yHat
        print 'y'
        print y
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        print 'print delta3'
        print delta3
        print 'self.W2.T'
        print self.W2.T
        print 'self.z2'
        print self.z2
        #delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        delta2 = np.dot(delta3, self.W2.T)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))
        

In [328]:
NN = Neural_Network()

In [329]:
X = numpyMatrix
y = np.array([[16.0], [9.0], [4.0], [4.0]])

In [330]:
yHat = NN.forward(X)
print y

[[ 16.]
 [  9.]
 [  4.]
 [  4.]]


In [331]:
epsilon = 1e-4
x = 1.5

In [332]:
cost1 = NN.costFunction(X,y)
print cost1

[ 202.84670595]


In [341]:
grad = NN.computeGradients(X,y)
grad

yhat
[[-0.35467747]
 [-0.48149395]
 [-0.3046001 ]
 [-1.45798746]]
y
[[ 16.]
 [  9.]
 [  4.]
 [  4.]]


AttributeError: 'Neural_Network' object has no attribute 'z3'

In [333]:
computeNumericalGradient(NN, X, y)

array([-11.23527218,   1.27640757,   7.58371895,  -0.86156491,
         1.6589858 ,  -0.1884727 ,   4.42910726,  -0.50317838,
         8.74957744,  -0.57214143])

In [325]:
def computeNumericalGradient(N, X, y):
        paramsInitial = N.getParams()
        numgrad = np.zeros(paramsInitial.shape)
        perturb = np.zeros(paramsInitial.shape)
        e = 1e-4
        #print paramsInitial
        for p in range(len(paramsInitial)):
            #Set perturbation vector
            perturb[p] = e
            N.setParams(paramsInitial + perturb)
            loss2 = N.costFunction(X, y)
            
            N.setParams(paramsInitial - perturb)
            loss1 = N.costFunction(X, y)

            #Compute Numerical Gradient
            #print loss1
            #print loss2
            numgrad[p] = (loss2 - loss1) / (2*e)

            #Return the value we changed to zero:
            perturb[p] = 0
            
        #Return Params to original value:
        N.setParams(paramsInitial)

        return numgrad 

In [118]:
X

array([[ 0.14046768, -0.02199568, -0.02092104, -0.01849576],
       [ 0.1427455 , -0.16830751, -0.02092104, -0.03981317],
       [-0.21255957, -0.24198227, -0.02092104, -0.15176253],
       [ 0.42287642, -0.07463533, -0.02092104, -0.12002358]])

In [119]:
yHat

array([[ 0.25471265],
       [ 0.25125597],
       [ 0.27917574],
       [ 0.22576878]])

In [132]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 4
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))
        

In [135]:
def computeNumericalGradient(N, X, y):
        paramsInitial = N.getParams()
        numgrad = np.zeros(paramsInitial.shape)
        perturb = np.zeros(paramsInitial.shape)
        e = 1e-4

        for p in range(len(paramsInitial)):
            #Set perturbation vector
            perturb[p] = e
            N.setParams(paramsInitial + perturb)
            loss2 = N.costFunction(X, y)
            
            N.setParams(paramsInitial - perturb)
            loss1 = N.costFunction(X, y)

            #Compute Numerical Gradient
            numgrad[p] = (loss2 - loss1) / (2*e)

            #Return the value we changed to zero:
            perturb[p] = 0
            
        #Return Params to original value:
        N.setParams(paramsInitial)

        return numgrad 

In [50]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 2
        self.outputLayerSize = 1
        self.hiddenLayerSize = 3
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))
        

In [340]:
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))   
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = computeNumericalGradient(self.N, X, y)
        
        return cost, grad
        
    def train(self, X, y):
        #Make an internal variable for the callback function:
        self.X = X
        self.y = y

        #Make empty list to store costs:
        self.J = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(X, y), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res
    

In [121]:
from scipy import optimize